version: '3.4'

services:
  simonevcentralfront:
    image: simonevcentralbackend
    depends_on:
    - db
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_PORT=3306
      - DATABASE_HOST=db
      - DATABASE_USER=evr
      - DATABASE_PASSWORD=mypwd
      - DATABASE_NAME=evr

    ports:
      - 3800:3800
      - 3100:3100
      - 8080:8080
  db:
      image: mariadb:10.3.9
      volumes:
          - data:/var/lib/mysql
      environment:
          - MYSQL_ROOT_PASSWORD=mypwd
          - MYSQL_DATABASE=evr
          - MYSQL_USER=evr
          - MYSQL_PASSWORD=mypwd
volumes:
    data: